// import { env } from '@/env.mjs'

export const siteConfig = {
  name: 'Aman Mirza',
  title: 'Aman Mirza | Front-end developer',
  description:
    "Hello, I'm Aman. I am front-end developer from Poland. I enjoy building sites and apps. My focus is React (Next.js).",
  keywords: [
    'Aman Mirza',
    'Front-end developer',
    'Poland',
    'React',
    'Next.js',
    'Web development',
    'Front-end',
    'UI/UX',
    'Responsive design',
    'JavaScript',
    'HTML',
    'CSS',
    'Portfolio',
    'Projects',
    'Website',
    'Web applications',
    'Developer',
    'Code',
    'Programming',
    'Tech enthusiast',
  ],
  creator: 'Build With Aman Mirza',
  url: '#',
  contact: {
    email: 'aman9811269898@gmail.com',
    linkedin: 'https://www.linkedin.com/in/aman-mirza-4b15122aa/',
    github: 'https://github.com/AmanMirza9898',
  },
  links: {
    contactForm: '/#contact',
    linkedin: 'https://www.linkedin.com/in/aman-mirza-4b15122aa/',
    github: 'https://github.com/AmanMirza9898',
    mailTo: 'mailto:aman9811269898@gmail.com',
    cvPdf: '#',
    youtube: '#',
  },
}
